import os
import json
import urllib.request
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime

USER_AGENT = "Minenager/1.0"
MINECRAFT_DIR = Path("/data/minecraft")

def _download_to_file(url: str, dest_path: Path):
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=90) as resp, open(dest_path, "wb") as out_file:
        out_file.write(resp.read())

def _fetch_json(url: str) -> Any:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=25) as resp:
        return json.loads(resp.read().decode('utf-8'))

def _get_fabric_installer_version() -> str:
    """Fetch latest stable Fabric installer version from Fabric Meta API."""
    try:
        installers = _fetch_json("https://meta.fabricmc.net/v2/versions/installer")
        for inst in installers:
            if inst.get("stable"):
                return inst["version"]
        return installers[0]["version"]
    except Exception as e:
        print(f"Could not fetch Fabric installer version: {e}")
        return "1.0.1"

def _get_quilt_installer_version() -> str:
    """Fetch latest stable Quilt installer version from Quilt Meta API."""
    try:
        installers = _fetch_json("https://meta.quiltmc.org/v3/versions/installer")
        for inst in installers:
            if inst.get("stable"):
                return inst["version"]
        return installers[0]["version"]
    except Exception as e:
        print(f"Could not fetch Quilt installer version: {e}")
        return "0.11.2"

def ensure_server_properties():
    """Ensure server.properties exists and strictly maintains server-port=25565."""
    props_file = MINECRAFT_DIR / "server.properties"
    default_props = (
        "# Minecraft Server Properties\n"
        "# Generated by Dashboard\n"
        "server-port=25565\n"
        "query.port=25565\n"
        "gamemode=survival\n"
        "difficulty=easy\n"
        "max-players=20\n"
        "online-mode=true\n"
        "pvp=true\n"
        "view-distance=10\n"
        "simulation-distance=10\n"
    )
    if not props_file.exists():
        with open(props_file, "w") as f:
            f.write(default_props)
    else:
        # Guarantee server-port=25565 is preserved
        with open(props_file, "r") as f:
            content = f.read()
        if "server-port=" in content:
            lines = []
            for line in content.splitlines():
                if line.strip().startswith("server-port="):
                    lines.append("server-port=25565")
                else:
                    lines.append(line)
            content = "\n".join(lines) + "\n"
        else:
            content += "\nserver-port=25565\n"
        with open(props_file, "w") as f:
            f.write(content)

def get_loader_versions(mc_version: str, loader: str) -> List[str]:
    """Fetch available loader versions for a specific Minecraft version and loader."""
    loader_clean = (loader or "fabric").lower().strip()
    try:
        if loader_clean in ["fabric", "fabric-loader"]:
            meta_url = f"https://meta.fabricmc.net/v2/versions/loader/{mc_version}"
            data = _fetch_json(meta_url)
            return [item["loader"]["version"] for item in data if "loader" in item][:20]
        elif loader_clean in ["quilt", "quilt-loader"]:
            meta_url = f"https://meta.quiltmc.org/v3/versions/loader/{mc_version}"
            data = _fetch_json(meta_url)
            return [item["loader"]["version"] for item in data if "loader" in item][:20]
        elif loader_clean in ["vanilla"]:
            return ["Official"]
        else:
            return ["Latest", "Recommended"]
    except Exception as e:
        print(f"Error fetching loader versions for {loader_clean} {mc_version}: {e}")
        return ["Latest"]

def download_vanilla_server(mc_version: str) -> Path:
    """Download official Mojang vanilla server.jar."""
    manifest_url = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
    manifest = _fetch_json(manifest_url)
    
    version_entry = next((v for v in manifest.get("versions", []) if v["id"] == mc_version), None)
    if not version_entry:
        raise Exception(f"Minecraft version {mc_version} not found in Mojang manifest.")

    version_data = _fetch_json(version_entry["url"])
    server_download = version_data.get("downloads", {}).get("server", {})
    server_url = server_download.get("url")
    
    if not server_url:
        raise Exception(f"No server jar available for Minecraft {mc_version}.")

    dest_path = MINECRAFT_DIR / "server.jar"
    _download_to_file(server_url, dest_path)
    return dest_path

def download_fabric_server(mc_version: str, loader_version: Optional[str] = None) -> Path:
    """Download Fabric server launcher jar via Fabric Meta API with proper installer version."""
    if not loader_version or loader_version.lower() in ["latest", "recommended"]:
        meta_url = f"https://meta.fabricmc.net/v2/versions/loader/{mc_version}"
        loaders = _fetch_json(meta_url)
        if not loaders:
            raise Exception(f"No Fabric loader found for Minecraft version {mc_version}.")
        loader_version = loaders[0]["loader"]["version"]

    installer_version = _get_fabric_installer_version()
    # Correct 3-part URL scheme required by Fabric Meta API:
    # https://meta.fabricmc.net/v2/versions/loader/:game_version/:loader_version/:installer_version/server/jar
    server_jar_url = f"https://meta.fabricmc.net/v2/versions/loader/{mc_version}/{loader_version}/{installer_version}/server/jar"
    dest_path = MINECRAFT_DIR / "server.jar"
    _download_to_file(server_jar_url, dest_path)
    return dest_path

def download_quilt_server(mc_version: str, loader_version: Optional[str] = None) -> Path:
    """Download Quilt server launcher jar via Quilt Meta API with proper installer version."""
    if not loader_version or loader_version.lower() in ["latest", "recommended"]:
        meta_url = f"https://meta.quiltmc.org/v3/versions/loader/{mc_version}"
        loaders = _fetch_json(meta_url)
        if not loaders:
            raise Exception(f"No Quilt loader found for Minecraft version {mc_version}.")
        loader_version = loaders[0]["loader"]["version"]

    installer_version = _get_quilt_installer_version()
    server_jar_url = f"https://meta.quiltmc.org/v3/versions/loader/{mc_version}/{loader_version}/{installer_version}/server/jar"
    dest_path = MINECRAFT_DIR / "server.jar"
    _download_to_file(server_jar_url, dest_path)
    return dest_path

def download_server_loader_jar(mc_version: str, loader: str = "fabric", loader_version: Optional[str] = None) -> Dict[str, Any]:
    """Download the correct server jar for the requested loader and version."""
    MINECRAFT_DIR.mkdir(parents=True, exist_ok=True)
    loader_clean = (loader or "vanilla").lower().strip()

    jar_path = None
    if loader_clean in ["fabric", "fabric-loader"]:
        jar_path = download_fabric_server(mc_version, loader_version)
    elif loader_clean in ["quilt", "quilt-loader"]:
        jar_path = download_quilt_server(mc_version, loader_version)
    elif loader_clean in ["vanilla"]:
        jar_path = download_vanilla_server(mc_version)
    else:
        try:
            jar_path = download_fabric_server(mc_version, loader_version)
        except Exception:
            jar_path = download_vanilla_server(mc_version)

    # Auto-accept EULA
    eula_file = MINECRAFT_DIR / "eula.txt"
    with open(eula_file, "w") as f:
        f.write("# Generated by Minecraft Server Dashboard\neula=true\n")

    # Guarantee server.properties has server-port=25565
    ensure_server_properties()

    return {
        "success": True,
        "jar_path": str(jar_path),
        "jar_filename": jar_path.name if jar_path else "server.jar",
        "mc_version": mc_version,
        "loader": loader_clean,
        "loader_version": loader_version,
        "eula_accepted": True
    }

def install_custom_server(mc_version: str, loader: str, loader_version: Optional[str] = None) -> Dict[str, Any]:
    """Install server software and save instance.json."""
    res = download_server_loader_jar(mc_version, loader, loader_version)
    
    instance_info = {
        "name": f"Minecraft {mc_version}",
        "minecraft_version": mc_version,
        "loader": loader.lower(),
        "loader_version": res.get("loader_version") or loader_version or "latest",
        "server_jar": res.get("jar_filename", "server.jar"),
        "installed_at": datetime.utcnow().isoformat(),
        "type": "installer"
    }

    instance_file = MINECRAFT_DIR / "instance.json"
    with open(instance_file, "w") as f:
        json.dump(instance_info, f, indent=2)

    return {
        "success": True,
        "instance": instance_info
    }
