services:
  portal:
    build: .
    container_name: minenager-landing-portal
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_CLOUD_API_URL=http://localhost:8080/api/v1
